sudo: required
language: bash

before_install:
  - sudo apt-get install -y update
  - sudo apt-get install -y git
  - sudo apt-get install -y virtualbox-4.3
  - sudo apt-get install -y install vagrant
  - sudo apt-get install -y pandoc
  - gem install asciidoctor
  - vagrant box add https://vagrantcloud.com/truongdo/boxes/win10vs17/versions/0.1.0/providers/virtualbox.box

script:
   - git clone https://github.com/hemanth22/Pre-Release_hemanthindexpage.git

after_success:
 - push.sh

notifications:
  slack:
     rooms:
         - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#general
