sudo: required
language: bash
env:
  global:
#  - USER="hemanth22"
#  - EMAIL="hemanth22hemu@mail.com"
#  - REPO="Pre-Release_hemanthindexpage"
  - GH_REPO="github.com/${USER}/${DEST_REPO}.git"

before_install:
  - sudo apt-get -y install gcc make linux-headers-$(uname -r) dkms
  - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo sh -c 'echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" >> /etc/apt/sources.list'
  - sudo apt-get -y update
  - sudo apt-get install -y git
  - sudo apt-get install -y virtualbox-4.3
  - VBoxManage -v
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo apt-get install -y vagrant
  - sudo apt-get install -y pandoc
  - gem install asciidoctor

script:
   #- sudo vagrant box add windows107 https://vagrantcloud.com/truongdo/boxes/win10vs17/versions/0.1.0/providers/virtualbox.box
   #- sudo cp -rf ~/.vagrant.d/boxes/ /home/travis/build/hemanth22/Windows_VagrantRepo_VDE
   - vagrant -v

#after_success:
# - git remote
# - git config user.email ${EMAIL}
# - git config user.name ${USER}
# - git add .
# - git commit -m "Deployment process using deployer repository from Travis build  $TRAVIS_BUILD_NUMBER"
# - git push "https://${GITHUB_API_KEY}@${GH_REPO}" master

notifications:
  slack:
     rooms:
         - nothingorganization:GN1JzklSpbMyfZVWcS05U6a0#general
